### ISSUE TITLE
Powershell.

### ISSUE THREAD

**Issue by begin-theadventure** [DravenusRex/stalker-gamma-linux-guide#2]
Has this been tried? https://github.com/PietJankbal/powershell-wrapper-for-wine

**Comment by DravenusRex** [comment]
Not sure, if you make any progress, let us know.

**Comment by begin-theadventure** [comment]
I don't play the game however I knew about that project and wanted to know if it would work.
Doing it in a virtual machine seems tedious. 
There is also another way to Powershell in WINE (in case first wouldn't work): https://github.com/PietJankbal/Chocolatey-for-wine

**Comment by DravenusRex** [comment]
I don't have the ability to test right now, I'll leave the issue open, hopefully somebody else might try them out.
Thanks for the leads.

**Comment by cha0sbuster** [comment]
I gave these a shot; if there's a way to get them to work with the installer, I'm not aware of it. Chocolatey-for-Wine runs and works okay, but it doesn't fix the problem with running the installer.

The crux of the problem seems to be Microsoft Management Framework; a Windows component which Wine doesn't know what to do with the installer for. Theoretically it could be extracted and installed manually, but whether it would even work is up in the air, given that clearly Wine doesn't have proper support for PS 2.0.

If Grok made the installer open-source, it probably wouldn't be that much work to port it to Bash, lol.

**Comment by Dwegg0** [comment]
Why would the Installer even be closed, seems very odd to me for a such software to be closed.

**Comment by Dwegg0** [comment]
From experience, Grok is not to be trusted until he is man enough to open up the installer.

**Comment by cha0sbuster** [comment]
> Why would the Installer even be closed, seems very odd to me for a such software to be closed.

He's in the process of rewriting it, and it'll be cross-platform when that happens. It's likely he doesn't want to deal with maintaining an open-source version of the current installer.

**Comment by begin-theadventure** [comment]
Thanks cha0sbuster for testing, closing.
